[package]
name = "jogen-cli"
version.workspace = true
edition.workspace = true

[dependencies]

jogen-core = { path = "../core" }

clap = { version = "4.5.53", features = ["cargo", "derive"] }
anyhow.workspace = true
colored = "3.0.0"
chrono = "0.4.42"
