[package]
name = "jogen-cli"
version.workspace = true
edition.workspace = true

[dependencies]
jogen-core = { path = "../core" }

anyhow.workspace = true
clap.workspace = true

colored = "3.0.0"
chrono = "0.4.42"
