[package]
name = "jogen-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true

walkdir = "2.5.0"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
